version: "2"

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - sqlclosecheck
    - noctx
    - gosec

linters-settings:
  govet:
    enable:
      - shadow
  goimports:
    # 把本地包归为一组，避免混在第三方包里
    local-prefixes: github.com/your/project