version: "2"

linters:
  default: none
  enable:
    - gofmt
    - goimports
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - bodyclose
    - sqlclosecheck
    - noctx
    - gosec
  settings:
    govet:
      enable:
        - shadow